### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by FladeX** [nawa/node-kinopoisk-ru#1]
```
/node_modules/kinopoisk-ru/lib/kinopoisk.js:129
                    var id = /\/film\/(.+)\/sr\//.exec(href)[1];
                                                            ^

TypeError: Cannot read property '1' of null
    at /node_modules/kinopoisk-ru/lib/kinopoisk.js:129:61
    at Array.map (native)
    at Request._callback (/node_modules/kinopoisk-ru/lib/kinopoisk.js:127:18)
    at Request.self.callback (/node_modules/kinopoisk-ru/node_modules/request/request.js:121:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/node_modules/kinopoisk-ru/node_modules/request/request.js:985:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/node_modules/kinopoisk-ru/node_modules/request/request.js:936:12)
```

**Comment by nawa** [comment]
Could you provide the parameters of `search()` that was called?

**Comment by FladeX** [comment]
`kinopoisk.search('Волки и овцы: бе-е-е-зумное превращение', null, function(searchError, result) {});`
— for this movie http://www.kinopoisk.ru/film/738950/

`kinopoisk.search('Белоснежка и охотник 2', null, function(searchError, result) {});`
— for this movie http://www.kinopoisk.ru/film/680394/

**Comment by nawa** [comment]
@FladeX fixed in v.1.0.2

**Comment by FladeX** [comment]
Thanks! :+1:
